### ISSUE TITLE
[security] npms.io thinks the node-readability is insecure?

### ISSUE THREAD

**Issue by Bin-Huang** [luin/readability#106]
Excuse me. When I search node-readability  on the website https://npms.io/. And npms.io thinks it is insecure because of its dependencies.
Details: 
https://nodesecurity.io/check/node-readability

Maybe should update or replace some dependencies?

One more word, the package is good job and helpful.

**Comment by prijindal** [comment]
So does snyk: https://app.snyk.io/test/npm/node-readability/3.0.0
It is because of the older version of request they are using, they have updated the request version to 2.8.1 on github but it is not published on npm. The npm version is still using request version 2.4.0
