### ISSUE TITLE
Running node-readability in electron (node.js 0.11.13)

### ISSUE THREAD

**Issue by lolorama** [luin/readability#54]
Hi. Can't resolve this issue. Can you help?

Using node-readability in electron (https://github.com/atom/electron)

After plain install I've got "Uncaught Error: Could not locate the bindings file."
Then  after "node-gyp rebuild" I've got this:

```
Uncaught Error: Module version mismatch. Expected 44, got 14.", source: 
/path_to_project/node_modules/node-
readability/node_modules/jsdom/node_modules/contextify/node_modules/bindings/bindings.js
```

Is it possible to run node-readablility under node.js 0.11.x?

**Comment by luin** [comment]
Does `rm -rf node_modules` and run `npm install` again help?

**Comment by lolorama** [comment]
Nope. I've tried ```npm install``` and ```aspm install```, it doesn't help.
