### ISSUE TITLE
io.js v3 support

### ISSUE THREAD

**Issue by chrisyip** [luin/readability#55]
Since `jsdom` doesn't support `node.js` <= 0.12 anymore:

> Note that as of our 4.0.0 release, jsdom no longer works with Node.js™ (why?), and instead requires io.js (which is planned to replace Node.js™).

And `jsdom <= 3.x` could not be installed on `io.js`:

```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/Chris/.nvm/versions/io.js/v3.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/Users/Chris/.nvm/versions/io.js/v3.2.0/bin/iojs" "/Users/Chris/.nvm/versions/io.js/v3.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Chris/Workspace/demo/node_modules/jsdom/node_modules/contextify
```

So I suggest:

- Drop `node.js <= 0.12` and `io.js v1.x` (coz there's [an installaion issue with `io.js v1.x`](https://travis-ci.org/chrisyip/readability/jobs/78729058#L178)). Or
- Switch to [cheerio](https://github.com/cheeriojs/cheerio) (Note: we may need to implement `iframe` support)

**Comment by luin** [comment]
I'd like to bump a new version to use the latest version of jsdom in order to support io.js. It demands a great deal of work to switch to cheerio, much as I'd like to :-(

**Comment by chrisyip** [comment]
👍
