### ISSUE TITLE
both 2.0 or 1.* can not work for node.js v4.0

### ISSUE THREAD

**Issue by JohnnieFucker** [luin/readability#61]
node.js and  io.js are combine to one project as node.js v4.0,after upgrade my  node.js,both 2.0 or i.* can not work anymore,there's some dependencies modules version error.but i'm not sure which are.

js-bson: Failed to load c++ bson extension, using pure JS version
[Error: Module did not self-register.]

**Comment by luin** [comment]
Hi, It works on my machine:

![image](https://cloud.githubusercontent.com/assets/635902/10091644/aa989d1e-6370-11e5-8586-5c0e13407540.png)

This module doesn't depend on js-bson, could you please create an empty project and try again?

**Comment by JohnnieFucker** [comment]
sorry，it's my fault,the problems is a module which used by mongoose.thanks a lot.
