### ISSUE TITLE
Status of node.js support

### ISSUE THREAD

**Issue by aggied** [luin/readability#62]
The readme points out that io.js is slated to replace node.js -- everything I'm reading speaks to the opposite. Am I missing something, or will this repo switch gears back towards Node all is resolved?

**Comment by joshmarinacci** [comment]
io.js and node.js have merged back together to form node.js v4.  This is a recent development so the readme is probably out of date.

**Comment by luin** [comment]
Just updated the README. Thanks for pointing that out
