### ISSUE TITLE
Get text content

### ISSUE THREAD

**Issue by migreva** [luin/readability#67]
This library seems to be centered around HTML presentation, as the article seems to only return HTML-based properties.

I have a use case where I only care about the text in the article, and would love to get something like `article.text` that was just an array/string of the text of the article content.

Wondering if this is in the pipeline? Or if you would accept a PR for this?

**Comment by luin** [comment]
It should be easy to extract text with `article.document` using `textContent`, `innerText` or something similar.

**Comment by migreva** [comment]
I created a pull request that adds a .textBody property, can you check to see if this is something you would want?

https://github.com/luin/readability/pull/68
