### ISSUE TITLE
article

### ISSUE THREAD

**Issue by luchenqun** [luin/readability#84]
我正在做一个网络书签。我的需求是只想要article.title的内容。请问，能否通过配置，我拿到title内容之后，他就不再去获取网络内容。因为我见过测试，有些需要四五秒之后才将article内容获取完毕，这个时间对我来说有点长。

**Comment by jiangzhuo** [comment]
做书签的话可以直接考虑去获取<title>标签里的内容

**Comment by wong2** [comment]
plz close duplicate PRs
