### ISSUE TITLE
CLI problem

### ISSUE THREAD

**Issue by mathiasrw** [luin/readability#86]
I am getting 

    env: iojs: No such file or directory

whey trying to do anything via CLI. Any inputs?

**Comment by haroldtreen** [comment]
What CLI are you running? 

I'm unaware of any CLI interface for this package...

**Comment by mathiasrw** [comment]
Examples:

```bash
> readabillity --help
```


```bash
> readabillity --url www.google.com
```

The CLI is defined here https://github.com/luin/readability/blob/master/package.json#L12

and is implemented here https://github.com/luin/readability/blob/master/src/cli.js

**Comment by haroldtreen** [comment]
Oh wow! I obviously haven't poked around enough 😅 .

I haven't used the CLI - I'll see if I can reproduce your error.

**Comment by mathiasrw** [comment]
I found the wayyyy toooo wasy error - the enviroment is set to iojs (i just did not look propperly)

Fix PRed witn #87
