### ISSUE TITLE
Fetch CSS ?

### ISSUE THREAD

**Issue by LiTiang** [luin/readability#88]
I saw there're 2 image called before, after in u **README.md**

i think u dont provide such api to do that, right ?

so can u tell me how do u styling the web content after process by **_readability_** ? 

( just like the result u made --- **before.png** )

at now, i just use below code to fetch all guys in `<head>`
```
article.document.querySelector('head').innerHTML
```

**Comment by wong2** [comment]
apparently before.png is the original webpage, and after is the result of readability

**Comment by haroldtreen** [comment]
It would be interesting to have a library that preserved the styles, but I think that's out of scope for this project. The main focus here has been to analyze `html` and extract the main article. Figuring out how to transfer the styles to the extracted version is a separate concern.

Hope that answers the question. Going to close unless there's follow up.
