### ISSUE TITLE
Why is lightbox in unlikelyCandidatesRe?

### ISSUE THREAD

**Issue by wong2** [luin/readability#93]
it's very likely to be an image right?

**Comment by haroldtreen** [comment]
I didn't write the original regex, but I'm assuming it helps remove galleries?

Have you found some sites that are broken from this? I haven't come across any issues with it.

Hopefully that answers, but feel free to reopen if you have an argument for changing it.

**Comment by wong2** [comment]
@haroldtreen here is a bad case: https://zhuanlan.zhihu.com/p/28248770

**Comment by haroldtreen** [comment]
Thanks for that example!

In that case, I'm open to removing it.
