### ISSUE TITLE
Keeps skipping iframe

### ISSUE THREAD

**Issue by ceddyb** [luin/readability#98]
Is there a way to pull iframes aswell? for example an iframe from youtube

**Comment by ceddyb** [comment]
Looking through your sources, you imagine that a video from youtube will have an 'embed' element which is wrong, these days all youtube videos are enclosed in an iframe, 

i found a way to solve this, maybe i might do a PR,

It's just a single line i edited anyway

**Comment by ceddyb** [comment]
#99

**Comment by haroldtreen** [comment]
Where are you expecting to see the iframe? I don't have context on why the iframes are removed, but I don't believe that the extension searches within iframes for potential content. 

Is this just so that they are within jsdom when the extraction completes? I'm not following the use case for this.

**Comment by ceddyb** [comment]
@haroldtreen i wanted to extract youtube videos, but most are iframes. You remove iframes, some have youtube videos. i commented the line that removes iframes, will play with it later and valid if an iframe has a video. closing this now.
